export const MESSAGE_TYPE = {
  // dance (400 ~ 499)
  DANCE_MINI_GAME_READY_NOTIFICATION: 401,
  DANCE_READY_REQUEST: 402,
  DANCE_READY_NOTIFICATION: 403,
  DANCE_START_NOTIFICATION: 404,
  DANCE_TABLE_CREATE_REQUEST: 405,
  DANCE_TABLE_NOTIFICATION: 406,
  DANCE_KEY_PRESS_REQUEST: 407,
  DANCE_KEY_PRESS_RESPONSE: 408,
  DANCE_KEY_PRESS_NOTIFICATION: 409,
  DANCE_GAME_OVER_NOTIFICATION: 410,
  DANCE_CLOSE_SOCKET_NOTIFICATION: 411,
};
