export const FAIL_CODE = {
  NONE_FAILCODE: 0,
  UNKNOWN_ERROR: 1,
  INVALID_REQUEST: 2,
  AUTHENTICATION_FAILED: 3,
  CREATE_ROOM_FAILED: 4,
  JOIN_ROOM_FAILED: 5,
  LEAVE_ROOM_FAILED: 6,
  CHAT_FAIL: 7,
  GAME_PREPARE_FAIL: 8,
  BOARD_PLAYER_MOVE_FAIL: 9,
  TILE_PURCHASE_FAIL: 10,
  BACK_TO_THE_ROOM_FAIL: 11,
  INVALID_ROOM_STATE: 12,
  ID_OR_PASSWORD_MISS: 13, // 13 ~ 20 AUTH SERVER ERROR
  NOT_MATCH_PASSWORD_CONFIRM: 14,
  ALREADY_EXIST_ID: 15,
  ALREADY_LOGGED_IN_ID: 16,
};
