services:
  filebeat:
    image: super-convergence-msa-server-filebeat:${FILEBEAT_IMAGE_TAG}
    user: root  # 또는 적절한 사용자
    volumes:
    - /app/logs:/app/logs
    environment:
      - TZ=Asia/Seoul
      - ELK_SERVER=${ELK_SERVER}
    ports:
      - '7021:7021'
    networks:
      - super-convergence

networks:
  super-convergence:
    external: true

