import { MESSAGE_TYPE } from '@repo/common/header';
import IceServer from './classes/models/ice.server.class.js';
import { SERVER_HOST } from './constants/env.js';

const SERVER_NAME = 'ice';
const SERVER_PORT = 7016;

const server = new IceServer(SERVER_NAME, SERVER_PORT, [
  MESSAGE_TYPE.ICE_MINI_GAME_READY_NOTIFICATION,
  MESSAGE_TYPE.ICE_GAME_READY_REQUEST,
  MESSAGE_TYPE.ICE_GAME_READY_NOTIFICATION,
  MESSAGE_TYPE.ICE_MINI_GAME_START_NOTIFICATION,
  MESSAGE_TYPE.ICE_PLAYER_SYNC_REQUEST,
  MESSAGE_TYPE.ICE_PLAYERS_SYNC_NOTIFICATION,
  MESSAGE_TYPE.ICE_PLAYER_DAMAGE_REQUEST,
  MESSAGE_TYPE.ICE_PLAYER_DAMAGE_NOTIFICATION,
  MESSAGE_TYPE.ICE_PLAYER_DEATH_NOTIFICATION,
  MESSAGE_TYPE.ICE_GAME_OVER_NOTIFICATION,
  MESSAGE_TYPE.ICE_MAP_SYNC_NOTIFICATION,
]);

await server.start();

server.connectToDistributor(SERVER_HOST, 7010, (data) => {
  // Distributor 연결
  console.log('Distributor Notification', data);
});
