export const MESSAGE_TYPE = {
  // Lobby (11-30)
  LOBBY_JOIN_REQUEST: 11,
  LOBBY_CHAT_REQUEST: 12,
  LOBBY_CHAT_RESPONSE: 13,
  LOBBY_NOTIFICATION: 14,
  LOBBY_USER_LIST_NOTIFICATION: 15,
  LOBBY_USER_DETAIL_REQUEST: 16,
  LOBBY_USER_DETAIL_RESPONSE: 17,

  // Room (31~50)
  ROOM_LIST_REQUEST: 31,
  ROOM_LIST_RESPONSE: 32,
  CREATE_ROOM_REQUEST: 33,
  CREATE_ROOM_RESPONSE: 34,
  JOIN_ROOM_REQUEST: 35,
  JOIN_ROOM_RESPONSE: 36,
  JOIN_ROOM_NOTIFICATION: 37,
  LEAVE_ROOM_REQUEST: 38,
  LEAVE_ROOM_RESPONSE: 39,
  LEAVE_ROOM_NOTIFICATION: 40,
};
