export const MESSAGE_TYPE = {
  // Lobby (11-30)
  LOBBY_JOIN_REQUEST: 11,
  LOBBY_CHAT_REQUEST: 12,
  LOBBY_CHAT_RESPONSE: 13,
  LOBBY_NOTIFICATION: 14,
  LOBBY_USER_LIST_NOTIFICATION: 15,
  LOBBY_USER_DETAIL_REQUEST: 16,
  LOBBY_USER_DETAIL_RESPONSE: 17,
};
