export const MESSAGE_TYPE = {
  // Lobby (11-30)
  LOBBY_JOIN_REQUEST: 11,
  LOBBY_JOIN_RESPONSE: 12,
  LOBBY_LEAVE_REQUEST: 13,
  LOBBY_LEAVE_RESPONSE: 14,
  LOBBY_USER_LIST_REQUEST: 15,
  LOBBY_USER_LIST_RESPONSE: 16,
  LOBBY_USER_DETAIL_REQUEST: 17,
  LOBBY_USER_DETAIL_RESPONSE: 18,
};
