export const MESSAGE_TYPE = {
  // Game start (51-60)
  GAME_START_REQUEST: 51,
  GAME_START_NOTIFICATION: 52,

  // Game Play (61-90)
  ROLL_DICE_REQUEST: 61,
  ROLL_DICE_RESPONSE: 62,
  ROLL_DICE_NOTIFICATION: 63,
  MOVE_PLAYER_BOARD_REQUEST: 64,
  MOVE_PLAYER_BOARD_RESPONSE: 65,
  MOVE_PLAYER_BOARD_NOTIFICATION: 66,
  PURCHASE_TILE_REQUEST: 67,
  PURCHASE_TILE_RESPONSE: 68,
  PURCHASE_TILE_NOTIFICATION: 69,
  GAME_END_NOTIFICATION: 70,

  // Post Game (91-100)
  BACK_TO_THE_ROOM_REQUEST: 91,
  BACK_TO_THE_ROOM_RESPONSE: 92,
  BACK_TO_THE_ROOM_NOTIFICATION: 93,
};
